sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf DMTN-068.pdf --upload --lsstdoc DMTN-068.tex --env=travis --ltd-product dmtn-068"
env:
  global:
    # Add LSST the Docs credentials
    - secure: "Hz52//YZSCiek1Cn6yazFwIx6YioeGCykMaT5aiHsBOlgEEyZCrGwpcT25nH+8boqDkuUgH+41o9vZmUGqPFgdaJ6BOnAFZfjG0rd2cWvWmHFfvnvfTjFose4NJAA0Lnq7xmkRaOsDCNatLz3thLrpJZSW2Pg7sf0ehALZxsDNhsqrAQaG3GV8m1LLmRKVMN4u6A+nfwMz0GDVCNXYvbg8d4uK6SBF2DUd2AxApV+1L/cf3nhfo5cm+nlp1fHFKSoUwKlPgWBC9teAFedh5U0+vyqlw2XlYPliHkbzqbUdE/zK5MJUFwkwY0OAFTsBJiuRHLBvElARHoow/5jmRFyLWQMm9NbrJTlBCiSfD10hOKNJnsIEKleXbJ9pgz6+j+ApAcYmCNLgYVAeSc3RAb/N9eeIOln9BO6pDTpRth9kAzZNeyMMeZdEYkEWF5nhhAlKzCOIYRjZpsWFIIoF/KudXuwmXQBSbfy75nSBUHVN8FpcweONZ7ztUxIVksZqek13xi3kBPZgJ6qlnMWxiRxDB7LcZLbP/b4jXORzcQdLIFokkFt5f/jietbNFCuB6FngESlCghNGoxl4+R1PDhbgufvzBqCklcBzcNjAu0TeMUG3bBBSi9PtujJ4SdJrbyb23uWM2+8OpxUFVNr+pG+RCOTOqY0hxhe0pxZb2osDk="
    - secure: "Hfyd/F9vGRk29HeVarslQHbYpEqhOOtitBdj0nDEx/TeKzw1yTghm/R+DPkXHakrMizRI0Z/hhaQUR6Z4ofZcDx3x7TV/tet4VT7gR+JOTglb3xMBtt+exoijKN3v0kSRJJoCrSWfXwIwpg1KuAVcLzu5EMTc1pTcwxrU2L5B+VAfV/wpeKBDO56GFWomBPLwoYBcPOub16JMNRE9SRLa0/we6yz4x4xNNJPgAQpXUVGVEIfG2/bqksxNAI7MteDBTutVChGnuJwAoK/lZa5Du1UKGoasruVqW3b1VSIBf5cboWTSDwhNpO7COJJQkzZk5nn9HVa+yUu5D6RHYoxejd4PuueeMB6QOfwpv08Hk7cfqAingJQYFnWch5ta2OtQPAtPNN+PZrgDvbwNLBZ1Y73plGM/qYkins3+wzwA1T9rlX24lBkF+bGrS18UygRvmFyJ/R9pUCQrRoq3PriLE5VozpcYHcrQwKwarG9Y4s3ha+/L48SD2sc92eNqiKMEE6eGRNCBzzu06xZbvtVzeVh8ad0fwZTsdXtCmlWNxY/z5mE77YdUQjf2NMhnjsEcZJ/xMiprgfSWNiS/Y5WXvxZ4k+oUZrm508O5FPndjjXor8Y0p/EtxIN/JhmkHNLMWM/qXgCqJm5E5V479/XhtxTc2EbahQxf/lj1dbk4Vw="
